[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"
  
  [build.environment]
    CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://chessmn-backend.onrender.com https://chessmn.onrender.com; connect-src 'self' https://chessmn-backend.onrender.com https://chessmn.onrender.com wss://chessmn.onrender.com https://*.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://firebaseinstallations.googleapis.com https://firestore.googleapis.com https://api.chess.com https://lichess.org; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com blob:; frame-src 'self' https://*.firebaseapp.com https://*.googleapis.com;"
